name: Deploy Backend to Droplet

on:
  push:
    branches:
      - main # Trigger this workflow on every push to the main branch
    paths:
      - 'backend/**' # Only run if files inside the /backend directory change

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend # Use the backend's Dockerfile
          push: true
          tags: jassi16/tradeoff-backend:latest

      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            cd /home/ubuntu/tradeoff-backend
            docker pull jassi16/tradeoff-backend:latest
            docker-compose -f docker-compose.prod.yml up -d --force-recreate